export class LaneData {
  public data: any[] = [
    {
      'createdOn': null,
      'publicLaneCode': '80',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': 'PARC (RUE DU)',
      'idLane': '996b5440-6c6d-4503-ab3d-94a4683928db',
      'brokeUpGenericCode': null,
      'genericCode': 'M',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': false,
      'brokeUpLaneCode': null,
      'idLanguageContentName': 'PARC',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '197E RUE',
      'idLane': '2cfae3aa-da6f-46fb-9ff2-21fa1bde1152',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '197E RUE',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '175E RUE',
      'idLane': '44d2cf8d-ffea-498f-a9f3-8228d2a64d2e',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '175E RUE',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '118E RUE',
      'idLane': '90bdcc45-fe19-4d5c-ba7f-b1afac6b844b',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '118E RUE',
      'lanePrefix': ''
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '141E RUE',
      'idLane': '7bdf4afa-374a-4d9a-b685-a4937b6feccf',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '141E RUE',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '178E RUE',
      'idLane': '084dba98-2119-40d3-a3c3-05d2964cf668',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '178E RUE',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '10E RUE',
      'idLane': 'ede41c4b-0319-416f-b2d7-c26548e000ef',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '10E RUE',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '80',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '20E (RUE)',
      'idLane': '8d912f8c-36a6-4ba2-bd67-cabb29dd36fc',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '20E',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '13E AVENUE',
      'idLane': '7cf70bca-f171-44ab-8084-dfa4c31c58b2',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '13E AVENUE',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '80',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': 'RODRIGUE (RUE)',
      'idLane': '32c3b045-c665-4789-936d-84dc25361521',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': false,
      'brokeUpLaneCode': null,
      'idLanguageContentName': 'RODRIGUE',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '80',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '45E (RUE)',
      'idLane': '33f43dad-cb84-46f1-ae76-99aa648148c5',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': 'NORD',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '45E',
      'lanePrefix': ''
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '95E RUE',
      'idLane': 'cecb9d73-8fc9-4859-b072-81d3719a656c',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '95E RUE',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '11',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': 'LACROIX (BOULEVARD)',
      'idLane': '8f21cafd-c188-4f62-8fe6-e4321a866ca8',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': 'LACROIX',
      'lanePrefix': ''
    },
    {
      'createdOn': null,
      'publicLaneCode': '01',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': '27E RUE NORD',
      'idLane': '08929f79-9298-4bcf-ae3b-1f3c1e3be2c0',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': '27E RUE NORD',
      'lanePrefix': null
    },
    {
      'createdOn': null,
      'publicLaneCode': '11',
      'idCity': '29bb0912-e4ce-45f0-8c26-511806d25b50',
      'isValid': true,
      'fullNameForFireCad': 'DIONNE (BOULEVARD)',
      'idLane': 'f6ada798-2dba-4480-9b82-46cf656adb4f',
      'brokeUpGenericCode': null,
      'genericCode': 'A',
      'brokeUpName': null,
      'publicLane': null,
      'direction': '',
      'isActive': true,
      'brokeUpLaneCode': null,
      'idLanguageContentName': 'DIONNE',
      'lanePrefix': ''
    }
  ];
}
